name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: vps

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug Secrets
        run: |
          echo "Checking if VPS_HOST is set..."
          if [ -n "${{ secrets.VPS_HOST }}" ]; then
            echo "VPS_HOST is set"
          else
            echo "VPS_HOST is NOT set"
          fi

          echo "Checking if VPS_SSH_KEY is set..."
          if [ -n "${{ secrets.VPS_SSH_KEY }}" ]; then
            echo "VPS_SSH_KEY is set"
          else
            echo "VPS_SSH_KEY is NOT set"
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          # Add any required environment variables here
          NODE_ENV: production

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: deploy
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/app
            sudo chown -R deploy:deploy .
            git config --global --add safe.directory /var/www/app
            git pull origin main
            docker-compose down
            docker-compose up -d --build
